---
title: "analy_data2"
author: "Manirath Wongsim"
date: "May 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
mpg.t.test <- t.test(MPG.highway ~ Origin, data = Cars93, conf.level = 0.90)
mpg.t.test
```


```{r}
phys.visit.binned <- birthwt$physician.visits
phys.visit.binned[phys.visit.binned >= 3] <- "3.or.more"
birthwt <- transform(birthwt, phys.visit.binned = as.factor(phys.visit.binned))

birthwt$phys.visit.binned

View(birthwt)

```

```{r}
aov.birthwt <- aov(birthwt.grams ~ phys.visit.binned, data = birthwt)
aov.birthwt

```


```{r}
birthwt.lm <- lm(birthwt.grams ~ mother.age + mother.smokes, data = birthwt)
summary(birthwt.lm)
plot(birthwt.lm)
```


```{r}
ggplot(birthwt, aes(x=mother.age, y=birthwt.grams, shape=mother.smokes, color=mother.smokes)) + 
  geom_point() + 
  geom_smooth(method = "lm") + 
  ylab("Birth Weight (grams)") + 
  xlab("Mother's Age (years)") + 
  ggtitle("Birth Weight by Mother's Age") 
```


```{r}
# Get new data set that no longer contains the outlier
birthwt.sub <- subset(birthwt, subset = mother.age < 40)

ggplot(birthwt.sub, aes(x=mother.age, y=birthwt.grams, shape=mother.smokes, color=mother.smokes)) + 
  geom_point() + # Adds points (scatterplot)
  geom_smooth(method = "lm") + # Adds regression lines
  ylab("Birth Weight (grams)") + # Changes y-axis label
  xlab("Mother's Age (years)") + # Changes x-axis label
  ggtitle("Birth Weight by Mother's Age") # Changes plot title
```






Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
